### ISSUE TITLE
custom hooks

### ISSUE THREAD

**Issue by brucou** [WebReflection/hooked-elements#1]
Hi there,

I was unable to ascertain whether custom hooks were possible. Would you be so kind to provide an example of custom hook if the functionality is indeed achievable with hooked-elements?

**Comment by WebReflection** [comment]
Can you point me to a custom hook example so I can reproduce it?
And btw, the answer is yes

**Comment by WebReflection** [comment]
so I went ahead and found [this article](https://itnext.io/react-custom-hooks-basics-f92de2a0ac0e) so that I've reproduced it in [here](https://codepen.io/WebReflection/pen/xxGgOQK?editors=0011).

That's the "_vanilla DOM_" version though, but these days I'd add 2.5K [uhtml](https://github.com/WebReflection/uhtml#readme) helper and write that very same example [as such](https://codepen.io/WebReflection/pen/xxGgOBx?editors=0011).

I hope these examples are good enough.

**Comment by brucou** [comment]
That works. There are a number of hooks implementation out there nowadays: ([TNG hooks](https://github.com/getify/TNG-Hooks) for example). ivi in my opinion [has the best way to do it](https://github.com/localvoid/ivi#hooks)). 

So, some don't allow using hooks in conditional clauses (like React), and that restricts custom hooks - a common pitfall is to move a conditional clause into the custom hook. So it is always safer to ask what are the restrictions if any which apply. As you make no mention of it, I assume that you do not suffer from the same limitations as React. In which case, it would nice to give an example of conditional hook that hooked-elements can hande and React cannot unless moving the conditional up or disappearing the conditional into a component. There is one example of conditionals here: https://dev.to/theonlybeardedbeast/conditional-hooks-maybe-18fk, or https://inventingwithmonster.io/20190207-break-the-rules-of-react-hooks/

**Comment by WebReflection** [comment]
> There are a number of hooks implementation out there nowadays

well, when I've written [augmentor](https://github.com/WebReflection/augmentor#readme), the library that brings hooks here or anywhere else, there were only React and TNG hooks, but the latter was at its debut without any ability to integrate `useEffect` via DOM nodes ... actually, IIRC, it had no `useEffect` at all, so as usual, I had to solve my use-cases by my own.

> some don't allow using hooks in conditional clauses (like React)

I've explained [how hooks work](https://medium.com/@WebReflection/demystifying-hooks-f55ad885609f) and conditional hooks are not part of the equation: these don't work, don't make sense, or branch out into non-optimized ways I would *not* recommend it.

On top of that, React is the one that brought hooks to the UI/render, so that diverging from what they do in any way, including different APIs like _ivi_ did, is not interesting, imho, but it's also likely less efficient and production size greedier than what you have here, which is a 2K, out of the box, no tools, polyfills, transpilers needed, library.

On top of that, I haven't seen any conditional hook in the _ivi_ documentation page, so if you mean conditional render, that's another story, as rendering has not much to do with hooks, rendering is handled in a different logical path.

> There is one example of conditionals here

The first example not only is called "_Conditional hooks, **maybe**_", but as soon as you read answers they say "_it's a mistake, don't do that_", like it is in [this one](https://dev.to/devdufutur/comment/hoh7)

Again, anyone understanding how hooks work inevitably understand conditional hooks are not the way ever, and it's explained in my previously linked post where I've documented how hooks work.

The last link you suggested it's all about **following hooks conventions**, and I start wondering if you've really read any of these articles before questioning me if this library enables conditional hooks: none of your links talk about conditional hooks, and conditional hooks are nothing developers should look for, rather the "_never do this in this way if you use hooks_" lesson they all should learn.

**Comment by brucou** [comment]
The second article I mentioned gives example of:
- using hooks conditionally: https://inventingwithmonster.io/20190207-break-the-rules-of-react-hooks/#running-hooks-conditionally
- using hooks in for loops: https://inventingwithmonster.io/20190207-break-the-rules-of-react-hooks/#running-hooks-within-a-loop

ivi does not have any problems with conditional, loops and what not.

**Comment by WebReflection** [comment]
@brucou I think you are not understanding those articles ... there is no conditional hooks in those articles.

By conditional, to be on the same page, I mean you cannot have a ternary operator that allows `useState` or `useRef` arbitrarily, and none of your links state that indeed.

> ivi does not have any problems with conditional, loops and what not.

there's not such thing as conditional loops: loops are loops, and the links you keep sharing explaing how to deal with loops, **solving** the _conditional_ issue.

**Comment by WebReflection** [comment]
I guess the culprit here is that _conditional_ can be obtained by workarounds, and every library that features hooks *will* be compatible with such workaround, but ternary hooks, as in:

```js
const what = condition ? useState(0) : useRef(0);
```

won't "_ever_" be a thing. If any library allows that, it means the library is not using hooks, it's doing something else.

_TL;DR_ augmentor is like React hooks, and React hooks *are* the meaning of Web hooks. If other libraries do things differently, it's not an augmentor concern, and it also doesn't make sense in the known "_Web hooks_" world.
