### ISSUE TITLE
Components in hooked-elements

### ISSUE THREAD

**Issue by kethan** [WebReflection/hooked-elements#4]
Can I use components in hooked-elements ? I see useeEffect clear function is not triggered. Do I need to call render in all the function I want to use this as component in react/preact.

Eg: https://codepen.io/kethan-the-selector/pen/vYdYKXr

I know there is uland, uce, etc. But I want to use it in this lib. Is that possible?

**Comment by WebReflection** [comment]
both wicked and hooked elements work with anything a querySelectorAll can reach, so the answer is yes, but if these components use shadow DOM then the answer is no, because if components are inside the shadow dom are not reachable via querySelector ... still you can reach `my-component` as selector, and then deal a part with their shadow dom, if any, and if public/open.
